--- 
- hosts: localhost
  tasks:
    - name: Create or Update Cloudformation stack
      cloudformation:
        stack_name: "javahome-stack-jenkins"
        region: "us-east-1"
        template: "javahome-stack.json"
        template_parameters:
          vpcCidr: "172.17.0.0/16"
          instanceTenancy: "default"
        state: "present"